Web/TechnicalBJJ.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace TechnicalBJJ.Web.Areas.Administration.Controllers
{
    using TechnicalBJJ.Common;
    using TechnicalBJJ.Web.Controllers;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

Web/TechnicalBJJ.Web/Controllers/BaseController.cs
namespace TechnicalBJJ.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

Web/TechnicalBJJ.Web/Controllers/HomeController.cs
namespace TechnicalBJJ.Web.Controllers
{
    using System.Diagnostics;

    using TechnicalBJJ.Web.ViewModels;

    using Microsoft.AspNetCore.Mvc;
    using TechnicalBJJ.Data;
    using System.Linq;
    using TechnicalBJJ.Data.Common.Repositories;
    using TechnicalBJJ.Data.Models;
    using TechnicalBJJ.Services.Data;
    using AutoMapper;
    using NToastNotify;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService getCountsService;
        private readonly IToastNotification toastNotification;

        // Implement automapper
        public HomeController(IGetCountsService getCountsService, IToastNotification toastNotification)
        {
            this.getCountsService = getCountsService;
            this.toastNotification = toastNotification;
        }

        public IActionResult Index()
        {
            var counts = this.getCountsService.GetCount();
            var viewModel = new IndexViewModel()
            {
                TechniquesCount = counts.TechniquesCount,
                StartingPositionsCount = counts.StartingPositionsCount,
                StepsCount = counts.StepsCount,
                ImagesCount = counts.ImagesCount,
                UsersCount = counts.UsersCount,
            };
            this.toastNotification.AddErrorToastMessage("Oss!");
            return this.View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/TechnicalBJJ.Web/Controllers/PositionController.cs
namespace TechnicalBJJ.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using TechnicalBJJ.Services.Data;
    using TechnicalBJJ.Web.ViewModels.InputModels;

    public class PositionController : Controller
    {
        private readonly IStartingPositionsService startingPositionsService;

        public PositionController(IStartingPositionsService startingPositionsService)
        {
            this.startingPositionsService = startingPositionsService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Add(AddPositionInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var inputModel = new AddPositionInputModel();
                return this.View(inputModel);
            }

            this.startingPositionsService.Add(input);
            return this.Redirect("/");
        }
    }
}

Web/TechnicalBJJ.Web/Controllers/TechniqueController.cs
namespace TechnicalBJJ.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using TechnicalBJJ.Data.Models;
    using TechnicalBJJ.Services.Data;
    using TechnicalBJJ.Web.ViewModels.InputModels;
    using TechnicalBJJ.Web.ViewModels.StartingPosition;
    using TechnicalBJJ.Web.ViewModels.Step;
    using TechnicalBJJ.Web.ViewModels.Technique;

    public class TechniqueController : Controller
    {
        private readonly ITechniqueService techniqueService;
        private readonly IStartingPositionsService startingPositionsService;
        private readonly UserManager<ApplicationUser> userManager;

        public TechniqueController(
            ITechniqueService techniqueService,
            IStartingPositionsService startingPositionsService,
            UserManager<ApplicationUser> userManager)
        {
            this.techniqueService = techniqueService;
            this.startingPositionsService = startingPositionsService;
            this.userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            var viewModel = new AddTechniqueInputModel();
            viewModel.StartingPositionsItems = this.startingPositionsService.GetStartingPositionsAsKeyValuePairs();
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddTechniqueInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var viewModel = new AddTechniqueInputModel();
                viewModel.StartingPositionsItems = this.startingPositionsService.GetStartingPositionsAsKeyValuePairs();
                return this.View(viewModel);
            }

            var userId = this.userManager.GetUserId(this.User);
            await this.techniqueService.AddAsync(input, userId);
            return this.Redirect("/");
        }

        // Techniques/All/5
        [HttpGet]
        public IActionResult AllTechniques(int id)
        {
            var viewModel = new TechniqueListViewModel();
            viewModel.PageNumber = id;


            var techniqueDtos = this.techniqueService.GetAllTechniques(id);

            foreach (var dto in techniqueDtos)
            {
                var techniqueInListViewModel = new TechniqueInListViewModel();

                var startingPositionViewModel = new StartingPositionViewModel();
                startingPositionViewModel.Name = dto.StartingPosition.Name;

                var techniqueSteps = new List<StepViewModel>();

                foreach (var stepDto in dto.Steps)
                {
                    var stepViewModel = new StepViewModel();
                    stepViewModel.Number = stepDto.Number;
                    stepViewModel.Description = stepDto.Description;

                    techniqueSteps.Add(stepViewModel);
                } 

                techniqueInListViewModel.Name = dto.Name;

                viewModel.Techniques.Add(techniqueInListViewModel);
            }

            return this.View(viewModel);
        }
    }
}

Web/TechnicalBJJ.Web/Views/Home/Index.cshtml
@using TechnicalBJJ.Common
@model TechnicalBJJ.Web.ViewModels.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
    <div class="col-md-4 offset-4">
        <p>We have:</p>
        <ul class="list-group shadow">
            <li class="list-group-item" id="techniquesRow">Techniques: @Model.TechniquesCount</li>
            <li class="list-group-item" id="startingPositionsRow">Starting Positions: @Model.StartingPositionsCount</li>
            <li class="list-group-item" id="stepsRow">Steps: @Model.StepsCount</li>
            <li class="list-group-item" id="imagesRow">Images: @Model.ImagesCount</li>
            <li class="list-group-item" id="usersRow">Users: @Model.UsersCount</li>
        </ul>
    </div>
</div>

Web/TechnicalBJJ.Web/Views/Position/Add.cshtml
@using TechnicalBJJ.Common.Enumerations;
@using TechnicalBJJ.Web.ViewModels.InputModels;
@{
    this.ViewData["Title"] = "Add new Position";
}
@model AddPositionInputModel


<form method="post" class="col-md-6 offset-md-3">
    <h1>@this.ViewData["Title"]</h1>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control shadow" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <input type="submit" class="btn btn-primary" />
</form>

Web/TechnicalBJJ.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using TechnicalBJJ.Common
@using TechnicalBJJ.Data.Models;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <img src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/bjj-logo-design-template-ee7d9864e60d5040766b14916cfce8c8_screen.jpg?ts=1678125373"
                     width="50"
                     style="border-radius:50%" />
                <a class="navbar-brand ms-4" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Technique" asp-action="Add">Add Technique</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Position" asp-action="Add">Add Position</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Technique" asp-action="AllTechniques">All Techniques</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container text-light">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName
        </div>
    </footer>
    <script src="~/css/" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify");
</body>
</html>

Web/TechnicalBJJ.Web/Views/Technique/Add.cshtml
@using TechnicalBJJ.Common.Enumerations;
@using TechnicalBJJ.Web.ViewModels.InputModels;
@{
    this.ViewData["Title"] = "Add new Technique";
    var categories = this.Model.StartingPositionsItems.Select(x => new SelectListItem(x.Value, x.Key));
}
@model AddTechniqueInputModel


<form method="post" class="col-md-6 offset-md-3">
    <h1>@this.ViewData["Title"]</h1>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control shadow" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="GiRequired"></label>
        <input asp-for="GiRequired" type="checkbox" id="giRequiredCheckbox" />
        <span asp-validation-for="GiRequired" class="text-danger"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control shadow" rows="5"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="BeltProficiency"></label>
        <select asp-for="BeltProficiency" class="form-control shadow"
                asp-items="@Html.GetEnumSelectList<BeltProficiency>()">
        </select>
        <span asp-validation-for="BeltProficiency" class="text-danger"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="Difficulty"></label>
        <select asp-for="Difficulty" class="form-control shadow"
                asp-items="@Html.GetEnumSelectList<Difficulty>()"></select>
        <span asp-validation-for="Difficulty" class="text-danger"></span>
    </div>

    <div class="form-group my-3">
        <label asp-for="StartingPositionId"></label>
        <select asp-for="StartingPositionId" class="form-control shadow"
                asp-items="@categories">
        </select>
        <span asp-validation-for="StartingPositionId" class="text-danger"></span>
    </div>

    <div class="form-group my-3" id="stepsContainer">
        <label asp-for="Steps"></label>
        <a class="btn btn-success shadow" onclick="addMoreSteps()">+</a>
    </div>

    <input type="submit" class="btn btn-primary"/>
</form>

@section Scripts{
    <script>
            var stepIndex = 0;
        function addMoreSteps(){
            $("#stepsContainer")
                .append("<div class='mt-2 clearfix'> <label> Step " + Number(stepIndex + 1) + " Description:</label> <textarea class='form-control my-2 shadow' name='Steps[" + stepIndex + "].Description'> </textarea></div> ");
            stepIndex++;
        }
    </script>
}

Web/TechnicalBJJ.Web/Views/Technique/AllTechniques.cshtml
@using TechnicalBJJ.Web.ViewModels.Technique;
@{
    this.ViewData["Title"] = "All Techniques";
}
@model TechniqueListViewModel

<h1>@this.ViewData["Title"]</h1>
<hr />
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var technique in Model.Techniques)
    {
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <img src="@technique.ImageUrl">
                    <h5 class="card-title">@technique.Name</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">StartingPosition: @technique.StartingPositionName</p>
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary">Publish Date : @technique.PublishDate</small>
                </div>
            </div>
        </div>
    }
</div>
<hr />
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>